// add action type constants i.e.:
const POST_COMMENT = "POST_COMMENT";
const GET_COMMENTS = "GET_COMMENTS";
const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
const GET_VIDINFO = "GET_VIDINFO";
const RECEIVE_VIDINFO = "RECEIVE_VIDINFO";
const SET_LINK = "SET_LINK";
const SET_TIME = "SET_TIME";

module.exports = {
    POST_COMMENT,
    GET_COMMENTS,
    RECEIVE_COMMENTS,
    GET_VIDINFO,
    RECEIVE_VIDINFO,
    SET_LINK,
    SET_TIME,
}